name: hooks_async_zone
description: "A new Flutter package project."
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  async_zone:
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
