name: workspace
description: "A new Flutter package project."

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

workspace:
  - packages/async_zone
  - packages/async_zone/example
  - packages/error_boundary
  - packages/error_boundary/example
  - packages/hooks_async_zone
  - packages/hooks_async_zone/example
  - packages/transition_boundary
  - packages/transition_boundary/example
  - examples/async_zone_sample
  - examples/fquery_sample
  - examples/riverpod_sample
  - examples/sliver_zone_sample
  - examples/stateful_zone_sample
  - examples/tanstack_query_sample
