name: transition_boundary_example
description: "Minimal example for transition_boundary."
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  async_zone:
  transition_boundary:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
